import { auth } from '@/lib/auth'
import { HTTPException } from 'hono/http-exception'
import { jstack } from 'jstack'

interface Env {
  Bindings: {}
}

export const j = jstack.init<Env>()

const allowlist = [
  'akashp1712@gmail.com',
  'akshathg7@gmail.com',
  'alvarofragosoc@gmail.com',
  'dtlvan@gmail.com',
  'harsh@formbricks.com',
  'hey@omidshabab.com',
  'jarrerh@gmail.com',
  'khoaizahmmed@gmail.com',
  'khvala@macpaw.com',
  'lindorf85@gmail.com',
  'liweizhismd@gmail.com',
  'luca@studiopiccinotti.it',
  'michel.binkhorst@xs4all.nl',
  'neske.joscha@gmail.com',
  'oluwaseunmauwedo@gmail.com',
  'p.homoky@gmail.com',
  'priart@gmail.com',
  'rohitmeshram000@gmail.com',
  'tommy.roman.hater@gmail.com',
  'vurukondasaiteja13@gmail.com',
  'joscha7676@gmail.com',
  'jcodog@cleoai.cloud',
  'hola@tomasholtz.com',
  'jorge@heyjorge.dev',
  'hello@joshtriedcoding.com',
  '8020ui@gmail.com',
  'danielcspaiva@gmail.com',
  'getoaarm1@gmail.com',
  'johnyeocx@gmail.com',
  'joscha7676@gmail.com',
  'me@nevillebrem.com',
  'myhappyagency@gmail.com',
  'ourrahmaan@gmail.com',
  'ratan.maurya@gmail.com',
  'stefanbinoj.007@gmail.com',
  'taikimingqu@gmail.com',
  'nizabizaher@gmail.com',
  'jokirillmeerkatz@outlook.de',
  '2607jojo@gmail.com',
  'pietro.dev.07@gmail.com',
  'lucapiccinotti.lp@gmail.com',
  'rathoursourabh5@gmail.com',
  'jonathan@fabworks.com',
  'justin.s.ragland@gmail.com',
  'shahram.ask.546@gmail.com',
  'hello@developeratul.com',
  'thepiyushchandwani@gmail.com',
  'jdaly2991@gmail.com',
  'dev.algomax@gmail.com',
  'vladanilic017@gmail.com',
  'heywinit@gmail.com',
  'chriszeuch.cz@gmail.com',
  'Danpvernon@gmail.com',
  'danpvernon@gmail.com',
  'ask199768@gmail.com',
  'theorcdev@gmail.com',
  'mazewinther@gmail.com',
  'vhchristophe@gmail.com',
  'oltian.kadriu@gmx.ch',
  'sahelmohamed55@gmail.com',
  'soumik.soumos7@gmail.com',
  'tinapple@gmail.com',
  'tanishq@rapidnode.xyz',
  'tristangabpinon@gmail.com',
  'vctrubio@gmail.com',
  'acollier@id.uff.br',
  'amagiddmxh@gmail.com',
  'iamcienlim@gmail.com',
  'jkalz@outlook.com',
  'joe@gotribe360.com',
  'tanweihup@gmail.com',
  'abdul@ema.co',
  'devsithi@gmail.com',
  'heitorstein@gmail.com',
  'jan@wilmake.com',
  'gordon.mickel@gmail.com',
  'lunging-manuals.0g@icloud.com',
  'nmhlahfir2@gmail.com',
  'stankovic.jovan.gg@gmail.com',
  'anthonylaflammex@gmail.com',
  'arsen@shkrumelyak.com',
  'atmuriv@yahoo.com',
  'connorbmahoney001@gmail.com',
  'jedceladez20@gmail.com',
  'ronakdoshi10@gmail.com',
  'yashdev.yvd@gmail.com',
  'shakilchyy@gmail.com',
  'adam.versed@gmail.com',
  'mail.bijsven@gmail.com',
  'rafaeluzzi@gmail.com',
  'sun@noru.app',
  'thomasbrooks106@gmail.com',
  'alahmadrosid@gmail.com',
  'christiancaneos1@gmail.com',
  'pranavkulkarni195@gmail.com',
  'shaheer.imran1429@gmail.com',
  'jcodog@jconet.co.uk',
  'moha@elguarir.dev',
  'stevef7fywmrp@gmail.com',
  'emilian.scheel@gmail.com',
  'spam@idk.com',
  'ziarparvaiz@gmail.com',
  'jp@hyperaide.com',
  'kanesmall@outlook.com',
  'aamak44@gmail.com',
  'ahmadalbourhan@gmail.com',
  'cameronjwblackwood@gmail.com',
  'cloud@agenticlabs.io',
  'thaitao2702@gmail.com',
  'virgileboris96@hotmail.fr',
  'yourwebdevprince@gmail.com',
  'ben@dee.mx',
  'contentport.evacuee271@dralias.com',
  'devrajchatribin9978@gmail.com',
  'pqoqubbw@gmail.com',
  'tommy@notaku.so',
  'bennwalsh7@gmail.com',
  'joework445@gmail.com',
  'lazaroblanc@gmail.com',
  'test@email.com',
  'ashishramachandran804@gmail.com',
  'yehonatanmind@gmail.com',
  'jan@alenix.de',
  'jekaksh@gmail.com',
  'oliviamurphy409@gmail.com',
  'angelobaricante@gmail.com',
  'daniel@dprctd.dev',
  'dingyimac@gmail.com',
  'tudor@pythia.social',
  'alacanatila@gmail.com',
  'austin@cpex.io',
  'takshtax@gmail.com',
  'whizibrahim@gmail.com',
  'sam@runpoint.ai',
  'subramanyeshwarak@gmail.com',
  'tomas.sivicki@gmail.com',
  'danieltriedcoding@gmail.com',
  'hey@dak.dev',
  'ishersingh16@gmail.com',
  'm6253272@gmail.com',
  'canarsiecode@gmail.com',
  'en.yske@gmail.com',
  'timi.medved@gmail.com',
  'jass@jass.gg',
  'maxim@datatino.de',
  'pooria.arab+contentport@gmail.com',
  'szymon.dlugolecki77@gmail.com',
  'busy.dislike830@passinbox.com',
  'deepshaswat@gmail.com',
  'ferrari4life@duck.com',
  'hosna599@gmail.com',
  'timofejs.zaruns@gmail.com',
  'uzair@districtzero.co',
  'samuelthegreat96@gmail.com',
  'trabelsi_hassan@yahoo.fr',
  'beingbilalashraf@gmail.com',
  'bmohak87@gmail.com'
]

const authMiddleware = j.middleware(async ({ c, next }) => {
  const session = await auth.api.getSession({ headers: c.req.raw.headers })

  if (!session) {
    throw new HTTPException(401, { message: 'Unauthorized' })
  }

  if (!allowlist.includes(session.user.email)) {
    throw new HTTPException(401, { message: 'Unauthorized' })
  }

  return await next({ user: session.user })
})

/**
 * Public (unauthenticated) procedures
 *
 * This is the base piece you use to build new queries and mutations on your API.
 */
export const publicProcedure = j.procedure
export const privateProcedure = publicProcedure.use(authMiddleware)
